<?php
  $translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Creator'),
        'value' => 'dcterms:creator'
    ],
    [
        'label' => $translate('Date'),
        'value' => 'dcterms:date'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>
<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2)."<br>"; ?>
    <h3><?php //echo $translate('Item set'); ?></h3>
    <!-- <div class="metadata">
        <?php// echo $itemSet->displayValues(); ?>
    </div> -->
    <div class="item-set-items">
    <?php  //echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>

</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($items as $item):
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
    $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
?>
    <li class="item resource">
        <a href=<?php echo $item->url()?> >
        <?php echo $this->thumbnail($item, 'medium'); ?>
            <?php if(strlen($heading) >= 95 ): ?>
              <h4><?php echo substr($heading, 0, 95 )."..."; ?></h4>
            <?php else: ?>
              <h4><?php echo $heading; ?></h4>
            <?php endif; ?>

              <?php if($item->value('dcterms:creator')): ?>
                <span><i class='fas fa-user-edit'></i> <?php echo $item->value('dcterms:creator'); ?> </span>
              <?php endif; ?>
              <?php if($item->value('dcterms:date')): ?>
                <br><span><i class='fas fa-calendar-day'></i> <?php echo $item->value('dcterms:date'); ?> </span>
              <?php endif; ?>
              <?php if($item->value('dcterms:publisher')): ?>
                <br><span><i class='fas fa-book'></i> <?php echo $item->value('dcterms:publisher'); ?> </span>
              <?php endif; ?>
              <?php if($item->value('dcterms:language')): ?>
                <br><span><i class='far fa-comments'></i> <?php echo $item->value('dcterms:language'); ?> </span>
              <?php endif; ?>
              <div class="abstract"><?php echo "<h4>Resumé:</h4>".$item->value('dcterms:abstract'); ?>
              </div>
        </a>
        <div class="abstractCard">
                  <div class="dropdown is-up">
                    <div class="dropdown-trigger">
                      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu2">
                        <span><?php echo $translate('Abstract'); ?></span>
                        <span class="icon is-small">
                          <i class="fas fa-angle-down" aria-hidden="true"></i>
                        </span>
                      </button>
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu2" role="menu">
                      <div class="dropdown-content">
                        <div class="dropdown-item">
                          <p><?php echo $item->value('dcterms:abstract'); ?></p>
                        </div>
                      </div>
                    </div>
                  </div>
        </div>
    </li>
<?php endforeach; ?>

</ul>

<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>
<script>
// Get all dropdowns on the page that aren't hoverable.
const dropdowns = document.querySelectorAll('.dropdown:not(.is-hoverable)');

if (dropdowns.length > 0) {
  // For each dropdown, add event handler to open on click.
  dropdowns.forEach(function(el) {
    el.addEventListener('click', function(e) {
      e.stopPropagation();
      el.classList.toggle('is-active');
    });
  });

  // If user clicks outside dropdown, close it.
  document.addEventListener('click', function(e) {
    closeDropdowns();
  });
}

/*
 * Close dropdowns by removing `is-active` class.
 */
function closeDropdowns() {
  dropdowns.forEach(function(el) {
    el.classList.remove('is-active');
  });
}

// Close dropdowns if ESC pressed
document.addEventListener('keydown', function (event) {
  let e = event || window.event;
  if (e.key === 'Esc' || e.key === 'Escape') {
    closeDropdowns();
  }
});
</script>
