<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.0/css/bulma.min.css');

$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
          <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }

            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .95;
            }
            <?php endif; ?>
        </style>
            <script src="https://kit.fontawesome.com/e6cac62c20.js" crossorigin="anonymous"></script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <!--<?php echo $userBar; ?>-->
        <header>
          <div class="logoDiv">
            <img class="logo-responsive" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <img class="logo" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <span class="site_title"> <?php echo $escape($siteTitle); ?> </span>
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
          </div>
            <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>
            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <div id="content" role="main">
            <?php echo $this->content; ?>


        </div>
      <?php $this->trigger('view.footer.before'); ?>

        <footer>

            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>

            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka'); ?>
            <?php endif; ?>
        </footer>
    </body>
</html>
